name: test-deployment

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-test:
    uses: vlabiitk/vlabs-workflows/.github/workflows/validate.yml@main
    secrets: inherit
